version: '2'
services:
  mysql:
   image: mysql:5.7
   volumes:
     - ./docker-data/mysql:/docker-entrypoint-initdb.d
   ports:
    - "13307:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     
  openldap:
    build: ./docker-data/openldap
    image: autentia/openldap
    ports:
      - 389:389
    environment:
      - SLAPD_DOMAIN=autentia.com
      - SLAPD_PASSWORD=adminadmin
      - SLAPD_CONFIG_PASSWORD=config
      - SLAPD_ADDITIONAL_SCHEMAS=ppolicy
      - SLAPD_ADDITIONAL_MODULES=ppolicy
    container_name: autentia-ldap
