spring:
  ldap:
     #urls: ldap://192.168.168.3:389/dc=autentia,dc=com
     #userDnPatterns: uid={0},ou=People
     urls: ldap://localhost:1389/dc=autentia,dc=com
     userDnPatterns: uid={0},ou=users

  datasource:
    name: myDataSource
    url: jdbc:mysql://localhost:13307/tntconcept?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

