spring:
  ldap:
     urls: ldap://localhost:389/dc=autentia,dc=com
     userDnPatterns: uid={0},ou=People

  datasource:
    name: myDataSource
    url: jdbc:mysql://localhost:13307/tntconcept?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

