spring:
  ldap:
    urls: ldap://localhost:1389/dc=autentia,dc=com
    userDnPatterns: uid={0},ou=users
    username: cn=admin,dc=autentia,dc=com
    password: adminadmin
    #urls: ldap://192.168.168.3:389/dc=autentia,dc=com
    #userDnPatterns: uid={0},ou=People
    user-dn-patterns: "uid={0}, ou=people"
    user-search-base: "ou=users"
    group-search-base: "ou=groups"
    group-search-filter: "(uniqueMember={0})"

  datasource:
    name: myDataSource
    url: jdbc:mysql://localhost:13307/tntconcept?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

client:
  name: tnt-mobile-angular
  secret: tnt-mobile-angular-secret
  scope: tnt
keystore:
  name: tnt
  pass: tnt
key:
  name: tnt
  pass: tnt

security:
  jwt:
    key:
      public: tnt-jwt-public-key
      private: tnt-jwt-private-keysadadasdasdasdasd

endpoints:
  auth:
    url: /oauth/**
