spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/testTnt?autoReconnect=true&useSSL=false
    username: test
    password: test
    
        
  jpa:
    generate-ddl: true
    hibernate:
      
      ddl-auto:  create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
      
    
