server:
  port: 8080

spring:

  profiles:
    active: prod

  ldap:
     urls: ldap://localhost:1389/dc=autentia,dc=com
     username: cn=admin,dc=autentia,dc=com
     password: adminadmin

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
  datasource:
    name: myDataSource
    url: jdbc:mysql://localhost:3306/tntconcept?autoReconnect=true&useSSL=false
    username: tnt
    password: tnt
    driver-class-name: com.mysql.jdbc.Driver